server:
  port: 8000
spring:
  application:
    name: ms-notification
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db_notification
      username: root
      password: root
      auto-index-creation: true
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest