server:
    port: 8080
spring:
    application:
        name: ms-user
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://mysql-service:3306/db_user?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
    jackson:
        time-zone: America/Sao_Paulo
        default-property-inclusion: NON_NULL
    rabbitmq:
        host: rabbitmq-service
        port: 5672
        username: guest
        password: guest
api:
    security:
        token:
            secret: ${JWT_SECRET:bXkgc2VjcmV0IGp3dA}

